name: ci
on:
  pull_request:
  push:
    branches:
      - main

env:
  ZIG_VERSION: 0.14.0

jobs:
  test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Run test suite 'minefield'
        run: zig build tests/minefield
      - name: Run test suite 'adversarial'
        run: zig build tests/adversarial
      - name: Run test suite 'examples'
        run: zig build tests/examples
      - name: Run test suite 'ondemand'
        run: zig build tests/ondemand
      - name: Run test suite 'schema'
        run: zig build tests/schema
      - name: Run test suite 'float parsing'
        run: zig build tests/float-parsing

  docs:
    name: Deploy documentation
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test

    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Generate documentation
        run: zig build docs

      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "zimdjson"
          directory: "zig-out/docs"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
